### ISSUE TITLE
Agregar Autoloader

### ISSUE THREAD

**Issue by waflessnet** [sascocl/LibreDTE#1]
Sería bueno agregarle un Autoloader para no llamar en duro el path de los Archivos , así se podría agregar a cualquer proyecto que use composer. 
(https://github.com/sascocl/LibreDTE/blob/master/lib/Sii/Autenticacion.php#L27)
Saludos.

**Comment by estebandelaf** [comment]
Se modificaron clases para ser compatibles con PSR-4. Se agregó autoloader a composer.

Saludos!
