### ISSUE TITLE
Minima version requerida 

### ISSUE THREAD

**Issue by waflessnet** [sascocl/LibreDTE#2]
hice pruebas con una solicitud token sobre PHP  5.4.43-1 bajando directamente con git y me funciona. Sin embargo al agregar el repositorio al composer.json me indica que la versión mínima requerida es 5.5 (https://github.com/sascocl/LibreDTE/blob/a29debd16823997996722892dab07f11ff8d0075/composer.json#L20)   

al composer.json lo agregue: 
...
```json
{
    "repositories": [
            {
            "type": "vcs",
                        "url": "https://github.com/sascocl/LibreDTE"
            }],
    "require": {
        "sasco/libredte": "dev-master"
            }
}
```
...

es estrictamente necesaria la 5.5 ?   podría ser >=5.4 ?

![image](https://cloud.githubusercontent.com/assets/6413704/9372050/860554c4-46b0-11e5-82a4-4c129b274255.png)

saludos.

**Comment by estebandelaf** [comment]
La biblioteca está siendo desarrollada de forma independiente a algún framework, sin embargo está pensabada para trabajar con SowerPHP, framework que utiliza PHP 5.5 o superior. Esto implica que se podrían utilizar características como generadores, list en foreach o finally en excepciones que están disponibles desde 5.5 sin previo aviso y sin liberar una nueva versión de la biblioteca.

Si bien actualmente no se podrían estar usando esas características, no significa que no se usen en el futuro, por esta razón se decidió requerir PHP 5.5 desde el principio.

Saludos!

**Comment by estebandelaf** [comment]
Para el envío del DTE se utiliza curl_file_create que
